using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Services;

namespace Models.Styles
{
    public class StyleDto 
    {
        public string StyleId { get; set; } = "0";
        public string? AccentColor { get; set; }
        public string? AlignContent { get; set; }
        public string? AlignItems { get; set; }
        public string? AlignSelf { get; set; }
        public string? All { get; set; }
        public string? Animation { get; set; }
        public string? AnimationDelay { get; set; }
        public string? AnimationDirection { get; set; }
        public string? AnimationDuration { get; set; }
        public string? AnimationFillMode { get; set; }
        public string? AnimationIterationCount { get; set; }
        public string? AnimationName { get; set; }
        public string? AnimationPlayState { get; set; }
        public string? AnimationTimingFunction { get; set; }
        public string? AspectRatio { get; set; }
        public string? BackdropFilter { get; set; }
        public string? BackfaceVisibility { get; set; }
        public string? Background { get; set; }
        public string? BackgroundAttachment { get; set; }
        public string? BackgroundBlendMode { get; set; }
        public string? BackgroundClip { get; set; }
        public string? BackgroundColor { get; set; }
        public string? BackgroundImage { get; set; }
        public string? BackgroundOrigin { get; set; }
        public string? BackgroundPosition { get; set; }
        public string? BackgroundPositionX { get; set; }
        public string? BackgroundPositionY { get; set; }
        public string? BackgroundRepeat { get; set; }
        public string? BackgroundSize { get; set; }
        public string? BlockSize { get; set; }
        public string? Border { get; set; }
        public string? BorderBlock { get; set; }
        public string? BorderBlockColor { get; set; }
        public string? BorderBlockEnd { get; set; }
        public string? BorderBlockEndColor { get; set; }
        public string? BorderBlockEndStyle { get; set; }
        public string? BorderBlockEndWidth { get; set; }
        public string? BorderBlockStart { get; set; }
        public string? BorderBlockStartColor { get; set; }
        public string? BorderBlockStartStyle { get; set; }
        public string? BorderBlockStartWidth { get; set; }
        public string? BorderBlockStyle { get; set; }
        public string? BorderBlockWidth { get; set; }
        public string? BorderBottom { get; set; }
        public string? BorderBottomColor { get; set; }
        public string? BorderBottomLeftRadius { get; set; }
        public string? BorderBottomRightRadius { get; set; }
        public string? BorderBottomStyle { get; set; }
        public string? BorderBottomWidth { get; set; }
        public string? BorderCollapse { get; set; }
        public string? BorderColor { get; set; }
        public string? BorderEndEndRadius { get; set; }
        public string? BorderEndStartRadius { get; set; }
        public string? BorderImage { get; set; }
        public string? BorderImageOutset { get; set; }
        public string? BorderImageRepeat { get; set; }
        public string? BorderImageSlice { get; set; }
        public string? BorderImageSource { get; set; }
        public string? BorderImageWidth { get; set; }
        public string? BorderInline { get; set; }
        public string? BorderInlineColor { get; set; }
        public string? BorderInlineEnd { get; set; }
        public string? BorderInlineEndColor { get; set; }
        public string? BorderInlineEndStyle { get; set; }
        public string? BorderInlineEndWidth { get; set; }
        public string? BorderInlineStart { get; set; }
        public string? BorderInlineStartColor { get; set; }
        public string? BorderInlineStartStyle { get; set; }
        public string? BorderInlineStartWidth { get; set; }
        public string? BorderInlineStyle { get; set; }
        public string? BorderInlineWidth { get; set; }
        public string? BorderLeft { get; set; }
        public string? BorderLeftColor { get; set; }
        public string? BorderLeftStyle { get; set; }
        public string? BorderLeftWidth { get; set; }
        public string? BorderRadius { get; set; }
        public string? BorderRight { get; set; }
        public string? BorderRightColor { get; set; }
        public string? BorderRightStyle { get; set; }
        public string? BorderRightWidth { get; set; }
        public string? BorderSpacing { get; set; }
        public string? BorderStartEndRadius { get; set; }
        public string? BorderStartStartRadius { get; set; }
        public string? BorderStyle { get; set; }
        public string? BorderTop { get; set; }
        public string? BorderTopColor { get; set; }
        public string? BorderTopLeftRadius { get; set; }
        public string? BorderTopRightRadius { get; set; }
        public string? BorderTopStyle { get; set; }
        public string? BorderTopWidth { get; set; }
        public string? BorderWidth { get; set; }
        public string? Bottom { get; set; }
        public string? BoxDecorationBreak { get; set; }
        public string? BoxReflect { get; set; }
        public string? BoxShadow { get; set; }
        public string? BoxSizing { get; set; }
        public string? BreakAfter { get; set; }
        public string? BreakBefore { get; set; }
        public string? BreakInside { get; set; }
        public string? CaptionSide { get; set; }
        public string? CaretColor { get; set; }
        public string? Clear { get; set; }
        public string? Clip { get; set; }
        public string? ClipPath { get; set; }
        public string? Color { get; set; }
        public string? ColorScheme { get; set; }
        public string? ColumnCount { get; set; }
        public string? ColumnFill { get; set; }
        public string? ColumnGap { get; set; }
        public string? ColumnRule { get; set; }
        public string? ColumnRuleColor { get; set; }
        public string? ColumnRuleStyle { get; set; }
        public string? ColumnRuleWidth { get; set; }
        public string? ColumnSpan { get; set; }
        public string? ColumnWidth { get; set; }
        public string? Columns { get; set; }
        public string? Content { get; set; }
        public string? CounterIncrement { get; set; }
        public string? CounterReset { get; set; }
        public string? CounterSet { get; set; }
        public string? Cursor { get; set; }
        public string? Direction { get; set; }
        public string? Display { get; set; }
        public string? EmptyCells { get; set; }
        public string? Filter { get; set; }
        public string? Flex { get; set; }
        public string? FlexBasis { get; set; }
        public string? FlexDirection { get; set; }
        public string? FlexFlow { get; set; }
        public string? FlexGrow { get; set; }
        public string? FlexShrink { get; set; }
        public string? FlexWrap { get; set; }
        public string? Float { get; set; }
        public string? Font { get; set; }
        public string? FontFamily { get; set; }
        public string? FontFeatureSettings { get; set; }
        public string? FontKerning { get; set; }
        public string? FontSize { get; set; }
        public string? FontSizeAdjust { get; set; }
        public string? FontStretch { get; set; }
        public string? FontStyle { get; set; }
        public string? FontVariant { get; set; }
        public string? FontVariantCaps { get; set; }
        public string? FontWeight { get; set; }
        public string? Gap { get; set; }
        public string? Grid { get; set; }
        public string? GridArea { get; set; }
        public string? GridAutoColumns { get; set; }
        public string? GridAutoFlow { get; set; }
        public string? GridAutoRows { get; set; }
        public string? GridColumn { get; set; }
        public string? GridColumnEnd { get; set; }
        public string? GridColumnStart { get; set; }
        public string? GridRow { get; set; }
        public string? GridRowEnd { get; set; }
        public string? GridRowStart { get; set; }
        public string? GridTemplate { get; set; }
        public string? GridTemplateAreas { get; set; }
        public string? GridTemplateColumns { get; set; }
        public string? GridTemplateRows { get; set; }
        public string? HangingPunctuation { get; set; }
        public string? Height { get; set; }
        public string? Hyphens { get; set; }
        public string? HyphenateCharacter { get; set; }
        public string? ImageRendering { get; set; }
        public string? InitialLetter { get; set; }
        public string? InlineSize { get; set; }
        public string? Inset { get; set; }
        public string? InsetBlock { get; set; }
        public string? InsetBlockEnd { get; set; }
        public string? InsetBlockStart { get; set; }
        public string? InsetInline { get; set; }
        public string? InsetInlineEnd { get; set; }
        public string? InsetInlineStart { get; set; }
        public string? Isolation { get; set; }
        public string? JustifyContent { get; set; }
        public string? JustifyItems { get; set; }
        public string? JustifySelf { get; set; }
        public string? Left { get; set; }
        public string? LetterSpacing { get; set; }
        public string? LineHeight { get; set; }
        public string? ListStyle { get; set; }
        public string? ListStyleImage { get; set; }
        public string? ListStylePosition { get; set; }
        public string? ListStyleType { get; set; }
        public string? Margin { get; set; }
        public string? MarginBlock { get; set; }
        public string? MarginBlockEnd { get; set; }
        public string? MarginBlockStart { get; set; }
        public string? MarginBottom { get; set; }
        public string? MarginInline { get; set; }
        public string? MarginInlineEnd { get; set; }
        public string? MarginInlineStart { get; set; }
        public string? MarginLeft { get; set; }
        public string? MarginRight { get; set; }
        public string? MarginTop { get; set; }
        public string? Marker { get; set; }
        public string? MarkerEnd { get; set; }
        public string? MarkerMid { get; set; }
        public string? MarkerStart { get; set; }
        public string? Mask { get; set; }
        public string? MaskClip { get; set; }
        public string? MaskComposite { get; set; }
        public string? MaskImage { get; set; }
        public string? MaskMode { get; set; }
        public string? MaskOrigin { get; set; }
        public string? MaskPosition { get; set; }
        public string? MaskRepeat { get; set; }
        public string? MaskSize { get; set; }
        public string? MaskType { get; set; }
        public string? MaxBlockSize { get; set; }
        public string? MaxHeight { get; set; }
        public string? MaxInlineSize { get; set; }
        public string? MaxWidth { get; set; }
        public string? MinBlockSize { get; set; }
        public string? MinInlineSize { get; set; }
        public string? MinHeight { get; set; }
        public string? MinWidth { get; set; }
        public string? MixBlendMode { get; set; }
        public string? ObjectFit { get; set; }
        public string? ObjectPosition { get; set; }
        public string? Offset { get; set; }
        public string? OffsetAnchor { get; set; }
        public string? OffsetDistance { get; set; }
        public string? OffsetPath { get; set; }
        public string? OffsetPosition { get; set; }
        public string? OffsetRotate { get; set; }
        public string? Opacity { get; set; }
        public string? Order { get; set; }
        public string? Orphans { get; set; }
        public string? Outline { get; set; }
        public string? OutlineColor { get; set; }
        public string? OutlineOffset { get; set; }
        public string? OutlineStyle { get; set; }
        public string? OutlineWidth { get; set; }
        public string? Overflow { get; set; }
        public string? OverflowAnchor { get; set; }
        public string? OverflowWrap { get; set; }
        public string? OverflowX { get; set; }
        public string? OverflowY { get; set; }
        public string? OverscrollBehavior { get; set; }
        public string? OverscrollBehaviorBlock { get; set; }
        public string? OverscrollBehaviorInline { get; set; }
        public string? OverscrollBehaviorX { get; set; }
        public string? OverscrollBehaviorY { get; set; }
        public string? Padding { get; set; }
        public string? PaddingBlock { get; set; }
        public string? PaddingBlockEnd { get; set; }
        public string? PaddingBlockStart { get; set; }
        public string? PaddingBottom { get; set; }
        public string? PaddingInline { get; set; }
        public string? PaddingInlineEnd { get; set; }
        public string? PaddingInlineStart { get; set; }
        public string? PaddingLeft { get; set; }
        public string? PaddingRight { get; set; }
        public string? PaddingTop { get; set; }
        public string? PageBreakAfter { get; set; }
        public string? PageBreakBefore { get; set; }
        public string? PageBreakInside { get; set; }
        public string? PaintOrder { get; set; }
        public string? Perspective { get; set; }
        public string? PerspectiveOrigin { get; set; }
        public string? PlaceContent { get; set; }
        public string? PlaceItems { get; set; }
        public string? PlaceSelf { get; set; }
        public string? PointerEvents { get; set; }
        public string? Position { get; set; }
        public string? Quotes { get; set; }
        public string? Resize { get; set; }
        public string? Right { get; set; }
        public string? Rotate { get; set; }
        public string? RowGap { get; set; }
        public string? Scale { get; set; }
        public string? ScrollBehavior { get; set; }
        public string? ScrollMargin { get; set; }
        public string? ScrollMarginBlock { get; set; }
        public string? ScrollMarginBlockEnd { get; set; }
        public string? ScrollMarginBlockStart { get; set; }
        public string? ScrollMarginBottom { get; set; }
        public string? ScrollMarginInline { get; set; }
        public string? ScrollMarginInlineEnd { get; set; }
        public string? ScrollMarginInlineStart { get; set; }
        public string? ScrollMarginLeft { get; set; }
        public string? ScrollMarginRight { get; set; }
        public string? ScrollMarginTop { get; set; }
        public string? ScrollPadding { get; set; }
        public string? ScrollPaddingBlock { get; set; }
        public string? ScrollPaddingBlockEnd { get; set; }
        public string? ScrollPaddingBlockStart { get; set; }
        public string? ScrollPaddingBottom { get; set; }
        public string? ScrollPaddingInline { get; set; }
        public string? ScrollPaddingInlineEnd { get; set; }
        public string? ScrollPaddingInlineStart { get; set; }
        public string? ScrollPaddingLeft { get; set; }
        public string? ScrollPaddingRight { get; set; }
        public string? ScrollPaddingTop { get; set; }
        public string? ScrollSnapAlign { get; set; }
        public string? ScrollSnapStop { get; set; }
        public string? ScrollSnapType { get; set; }
        public string? ScrollbarColor { get; set; }
        public string? ShapeOutside { get; set; }
        public string? TabSize { get; set; }
        public string? TableLayout { get; set; }
        public string? TextAlign { get; set; }
        public string? TextAlignLast { get; set; }
        public string? TextDecoration { get; set; }
        public string? TextDecorationColor { get; set; }
        public string? TextDecorationLine { get; set; }
        public string? TextDecorationStyle { get; set; }
        public string? TextDecorationThickness { get; set; }
        public string? TextEmphasis { get; set; }
        public string? TextEmphasisColor { get; set; }
        public string? TextEmphasisPosition { get; set; }
        public string? TextEmphasisStyle { get; set; }
        public string? TextIndent { get; set; }
        public string? TextJustify { get; set; }
        public string? TextOrientation { get; set; }
        public string? TextOverflow { get; set; }
        public string? TextShadow { get; set; }
        public string? TextTransform { get; set; }
        public string? TextUnderlineOffset { get; set; }
        public string? TextUnderlinePosition { get; set; }
        public string? Top { get; set; }
        public string? Transform { get; set; }
        public string? TransformOrigin { get; set; }
        public string? TransformStyle { get; set; }
        public string? Transition { get; set; }
        public string? TransitionDelay { get; set; }
        public string? TransitionDuration { get; set; }
        public string? TransitionProperty { get; set; }
        public string? TransitionTimingFunction { get; set; }
        public string? Translate { get; set; }
        public string? UnicodeBidi { get; set; }
        public string? UserSelect { get; set; }
        public string? VerticalAlign { get; set; }
        public string? Visibility { get; set; }
        public string? WhiteSpace { get; set; }
        public string? Widows { get; set; }
        public string? Width { get; set; }
        public string? WordBreak { get; set; }
        public string? WordSpacing { get; set; }
        public string? WordWrap { get; set; }
        public string? WritingMode { get; set; }
        public string? ZIndex { get; set; }
        public string? Zoom { get; set; }
    }
    
    [Table("Styles")] // Maps this entity to the "Cards" table
    public class Style: ICrudId
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long StyleId { get; set; }
         [NotMapped]
        public long Id { get => StyleId; set => StyleId = value; }
        public string? AccentColor { get; set; }
        public string? AlignContent { get; set; }
        public string? AlignItems { get; set; }
        public string? AlignSelf { get; set; }
        public string? All { get; set; }
        public string? Animation { get; set; }
        public string? AnimationDelay { get; set; }
        public string? AnimationDirection { get; set; }
        public string? AnimationDuration { get; set; }
        public string? AnimationFillMode { get; set; }
        public string? AnimationIterationCount { get; set; }
        public string? AnimationName { get; set; }
        public string? AnimationPlayState { get; set; }
        public string? AnimationTimingFunction { get; set; }
        public string? AspectRatio { get; set; }
        public string? BackdropFilter { get; set; }
        public string? BackfaceVisibility { get; set; }
        public string? Background { get; set; }
        public string? BackgroundAttachment { get; set; }
        public string? BackgroundBlendMode { get; set; }
        public string? BackgroundClip { get; set; }
        public string? BackgroundColor { get; set; }
        public string? BackgroundImage { get; set; }
        public string? BackgroundOrigin { get; set; }
        public string? BackgroundPosition { get; set; }
        public string? BackgroundPositionX { get; set; }
        public string? BackgroundPositionY { get; set; }
        public string? BackgroundRepeat { get; set; }
        public string? BackgroundSize { get; set; }
        public string? BlockSize { get; set; }
        public string? Border { get; set; }
        public string? BorderBlock { get; set; }
        public string? BorderBlockColor { get; set; }
        public string? BorderBlockEnd { get; set; }
        public string? BorderBlockEndColor { get; set; }
        public string? BorderBlockEndStyle { get; set; }
        public string? BorderBlockEndWidth { get; set; }
        public string? BorderBlockStart { get; set; }
        public string? BorderBlockStartColor { get; set; }
        public string? BorderBlockStartStyle { get; set; }
        public string? BorderBlockStartWidth { get; set; }
        public string? BorderBlockStyle { get; set; }
        public string? BorderBlockWidth { get; set; }
        public string? BorderBottom { get; set; }
        public string? BorderBottomColor { get; set; }
        public string? BorderBottomLeftRadius { get; set; }
        public string? BorderBottomRightRadius { get; set; }
        public string? BorderBottomStyle { get; set; }
        public string? BorderBottomWidth { get; set; }
        public string? BorderCollapse { get; set; }
        public string? BorderColor { get; set; }
        public string? BorderEndEndRadius { get; set; }
        public string? BorderEndStartRadius { get; set; }
        public string? BorderImage { get; set; }
        public string? BorderImageOutset { get; set; }
        public string? BorderImageRepeat { get; set; }
        public string? BorderImageSlice { get; set; }
        public string? BorderImageSource { get; set; }
        public string? BorderImageWidth { get; set; }
        public string? BorderInline { get; set; }
        public string? BorderInlineColor { get; set; }
        public string? BorderInlineEnd { get; set; }
        public string? BorderInlineEndColor { get; set; }
        public string? BorderInlineEndStyle { get; set; }
        public string? BorderInlineEndWidth { get; set; }
        public string? BorderInlineStart { get; set; }
        public string? BorderInlineStartColor { get; set; }
        public string? BorderInlineStartStyle { get; set; }
        public string? BorderInlineStartWidth { get; set; }
        public string? BorderInlineStyle { get; set; }
        public string? BorderInlineWidth { get; set; }
        public string? BorderLeft { get; set; }
        public string? BorderLeftColor { get; set; }
        public string? BorderLeftStyle { get; set; }
        public string? BorderLeftWidth { get; set; }
        public string? BorderRadius { get; set; }
        public string? BorderRight { get; set; }
        public string? BorderRightColor { get; set; }
        public string? BorderRightStyle { get; set; }
        public string? BorderRightWidth { get; set; }
        public string? BorderSpacing { get; set; }
        public string? BorderStartEndRadius { get; set; }
        public string? BorderStartStartRadius { get; set; }
        public string? BorderStyle { get; set; }
        public string? BorderTop { get; set; }
        public string? BorderTopColor { get; set; }
        public string? BorderTopLeftRadius { get; set; }
        public string? BorderTopRightRadius { get; set; }
        public string? BorderTopStyle { get; set; }
        public string? BorderTopWidth { get; set; }
        public string? BorderWidth { get; set; }
        public string? Bottom { get; set; }
        public string? BoxDecorationBreak { get; set; }
        public string? BoxReflect { get; set; }
        public string? BoxShadow { get; set; }
        public string? BoxSizing { get; set; }
        public string? BreakAfter { get; set; }
        public string? BreakBefore { get; set; }
        public string? BreakInside { get; set; }
        public string? CaptionSide { get; set; }
        public string? CaretColor { get; set; }
        public string? Clear { get; set; }
        public string? Clip { get; set; }
        public string? ClipPath { get; set; }
        public string? Color { get; set; }
        public string? ColorScheme { get; set; }
        public string? ColumnCount { get; set; }
        public string? ColumnFill { get; set; }
        public string? ColumnGap { get; set; }
        public string? ColumnRule { get; set; }
        public string? ColumnRuleColor { get; set; }
        public string? ColumnRuleStyle { get; set; }
        public string? ColumnRuleWidth { get; set; }
        public string? ColumnSpan { get; set; }
        public string? ColumnWidth { get; set; }
        public string? Columns { get; set; }
        public string? Content { get; set; }
        public string? CounterIncrement { get; set; }
        public string? CounterReset { get; set; }
        public string? CounterSet { get; set; }
        public string? Cursor { get; set; }
        public string? Direction { get; set; }
        public string? Display { get; set; }
        public string? EmptyCells { get; set; }
        public string? Filter { get; set; }
        public string? Flex { get; set; }
        public string? FlexBasis { get; set; }
        public string? FlexDirection { get; set; }
        public string? FlexFlow { get; set; }
        public string? FlexGrow { get; set; }
        public string? FlexShrink { get; set; }
        public string? FlexWrap { get; set; }
        public string? Float { get; set; }
        public string? Font { get; set; }
        public string? FontFamily { get; set; }
        public string? FontFeatureSettings { get; set; }
        public string? FontKerning { get; set; }
        public string? FontSize { get; set; }
        public string? FontSizeAdjust { get; set; }
        public string? FontStretch { get; set; }
        public string? FontStyle { get; set; }
        public string? FontVariant { get; set; }
        public string? FontVariantCaps { get; set; }
        public string? FontWeight { get; set; }
        public string? Gap { get; set; }
        public string? Grid { get; set; }
        public string? GridArea { get; set; }
        public string? GridAutoColumns { get; set; }
        public string? GridAutoFlow { get; set; }
        public string? GridAutoRows { get; set; }
        public string? GridColumn { get; set; }
        public string? GridColumnEnd { get; set; }
        public string? GridColumnStart { get; set; }
        public string? GridRow { get; set; }
        public string? GridRowEnd { get; set; }
        public string? GridRowStart { get; set; }
        public string? GridTemplate { get; set; }
        public string? GridTemplateAreas { get; set; }
        public string? GridTemplateColumns { get; set; }
        public string? GridTemplateRows { get; set; }
        public string? HangingPunctuation { get; set; }
        public string? Height { get; set; }
        public string? Hyphens { get; set; }
        public string? HyphenateCharacter { get; set; }
        public string? ImageRendering { get; set; }
        public string? InitialLetter { get; set; }
        public string? InlineSize { get; set; }
        public string? Inset { get; set; }
        public string? InsetBlock { get; set; }
        public string? InsetBlockEnd { get; set; }
        public string? InsetBlockStart { get; set; }
        public string? InsetInline { get; set; }
        public string? InsetInlineEnd { get; set; }
        public string? InsetInlineStart { get; set; }
        public string? Isolation { get; set; }
        public string? JustifyContent { get; set; }
        public string? JustifyItems { get; set; }
        public string? JustifySelf { get; set; }
        public string? Left { get; set; }
        public string? LetterSpacing { get; set; }
        public string? LineHeight { get; set; }
        public string? ListStyle { get; set; }
        public string? ListStyleImage { get; set; }
        public string? ListStylePosition { get; set; }
        public string? ListStyleType { get; set; }
        public string? Margin { get; set; }
        public string? MarginBlock { get; set; }
        public string? MarginBlockEnd { get; set; }
        public string? MarginBlockStart { get; set; }
        public string? MarginBottom { get; set; }
        public string? MarginInline { get; set; }
        public string? MarginInlineEnd { get; set; }
        public string? MarginInlineStart { get; set; }
        public string? MarginLeft { get; set; }
        public string? MarginRight { get; set; }
        public string? MarginTop { get; set; }
        public string? Marker { get; set; }
        public string? MarkerEnd { get; set; }
        public string? MarkerMid { get; set; }
        public string? MarkerStart { get; set; }
        public string? Mask { get; set; }
        public string? MaskClip { get; set; }
        public string? MaskComposite { get; set; }
        public string? MaskImage { get; set; }
        public string? MaskMode { get; set; }
        public string? MaskOrigin { get; set; }
        public string? MaskPosition { get; set; }
        public string? MaskRepeat { get; set; }
        public string? MaskSize { get; set; }
        public string? MaskType { get; set; }
        public string? MaxBlockSize { get; set; }
        public string? MaxHeight { get; set; }
        public string? MaxInlineSize { get; set; }
        public string? MaxWidth { get; set; }
        public string? MinBlockSize { get; set; }
        public string? MinInlineSize { get; set; }
        public string? MinHeight { get; set; }
        public string? MinWidth { get; set; }
        public string? MixBlendMode { get; set; }
        public string? ObjectFit { get; set; }
        public string? ObjectPosition { get; set; }
        public string? Offset { get; set; }
        public string? OffsetAnchor { get; set; }
        public string? OffsetDistance { get; set; }
        public string? OffsetPath { get; set; }
        public string? OffsetPosition { get; set; }
        public string? OffsetRotate { get; set; }
        public string? Opacity { get; set; }
        public string? Order { get; set; }
        public string? Orphans { get; set; }
        public string? Outline { get; set; }
        public string? OutlineColor { get; set; }
        public string? OutlineOffset { get; set; }
        public string? OutlineStyle { get; set; }
        public string? OutlineWidth { get; set; }
        public string? Overflow { get; set; }
        public string? OverflowAnchor { get; set; }
        public string? OverflowWrap { get; set; }
        public string? OverflowX { get; set; }
        public string? OverflowY { get; set; }
        public string? OverscrollBehavior { get; set; }
        public string? OverscrollBehaviorBlock { get; set; }
        public string? OverscrollBehaviorInline { get; set; }
        public string? OverscrollBehaviorX { get; set; }
        public string? OverscrollBehaviorY { get; set; }
        public string? Padding { get; set; }
        public string? PaddingBlock { get; set; }
        public string? PaddingBlockEnd { get; set; }
        public string? PaddingBlockStart { get; set; }
        public string? PaddingBottom { get; set; }
        public string? PaddingInline { get; set; }
        public string? PaddingInlineEnd { get; set; }
        public string? PaddingInlineStart { get; set; }
        public string? PaddingLeft { get; set; }
        public string? PaddingRight { get; set; }
        public string? PaddingTop { get; set; }
        public string? PageBreakAfter { get; set; }
        public string? PageBreakBefore { get; set; }
        public string? PageBreakInside { get; set; }
        public string? PaintOrder { get; set; }
        public string? Perspective { get; set; }
        public string? PerspectiveOrigin { get; set; }
        public string? PlaceContent { get; set; }
        public string? PlaceItems { get; set; }
        public string? PlaceSelf { get; set; }
        public string? PointerEvents { get; set; }
        public string? Position { get; set; }
        public string? Quotes { get; set; }
        public string? Resize { get; set; }
        public string? Right { get; set; }
        public string? Rotate { get; set; }
        public string? RowGap { get; set; }
        public string? Scale { get; set; }
        public string? ScrollBehavior { get; set; }
        public string? ScrollMargin { get; set; }
        public string? ScrollMarginBlock { get; set; }
        public string? ScrollMarginBlockEnd { get; set; }
        public string? ScrollMarginBlockStart { get; set; }
        public string? ScrollMarginBottom { get; set; }
        public string? ScrollMarginInline { get; set; }
        public string? ScrollMarginInlineEnd { get; set; }
        public string? ScrollMarginInlineStart { get; set; }
        public string? ScrollMarginLeft { get; set; }
        public string? ScrollMarginRight { get; set; }
        public string? ScrollMarginTop { get; set; }
        public string? ScrollPadding { get; set; }
        public string? ScrollPaddingBlock { get; set; }
        public string? ScrollPaddingBlockEnd { get; set; }
        public string? ScrollPaddingBlockStart { get; set; }
        public string? ScrollPaddingBottom { get; set; }
        public string? ScrollPaddingInline { get; set; }
        public string? ScrollPaddingInlineEnd { get; set; }
        public string? ScrollPaddingInlineStart { get; set; }
        public string? ScrollPaddingLeft { get; set; }
        public string? ScrollPaddingRight { get; set; }
        public string? ScrollPaddingTop { get; set; }
        public string? ScrollSnapAlign { get; set; }
        public string? ScrollSnapStop { get; set; }
        public string? ScrollSnapType { get; set; }
        public string? ScrollbarColor { get; set; }
        public string? ShapeOutside { get; set; }
        public string? TabSize { get; set; }
        public string? TableLayout { get; set; }
        public string? TextAlign { get; set; }
        public string? TextAlignLast { get; set; }
        public string? TextDecoration { get; set; }
        public string? TextDecorationColor { get; set; }
        public string? TextDecorationLine { get; set; }
        public string? TextDecorationStyle { get; set; }
        public string? TextDecorationThickness { get; set; }
        public string? TextEmphasis { get; set; }
        public string? TextEmphasisColor { get; set; }
        public string? TextEmphasisPosition { get; set; }
        public string? TextEmphasisStyle { get; set; }
        public string? TextIndent { get; set; }
        public string? TextJustify { get; set; }
        public string? TextOrientation { get; set; }
        public string? TextOverflow { get; set; }
        public string? TextShadow { get; set; }
        public string? TextTransform { get; set; }
        public string? TextUnderlineOffset { get; set; }
        public string? TextUnderlinePosition { get; set; }
        public string? Top { get; set; }
        public string? Transform { get; set; }
        public string? TransformOrigin { get; set; }
        public string? TransformStyle { get; set; }
        public string? Transition { get; set; }
        public string? TransitionDelay { get; set; }
        public string? TransitionDuration { get; set; }
        public string? TransitionProperty { get; set; }
        public string? TransitionTimingFunction { get; set; }
        public string? Translate { get; set; }
        public string? UnicodeBidi { get; set; }
        public string? UserSelect { get; set; }
        public string? VerticalAlign { get; set; }
        public string? Visibility { get; set; }
        public string? WhiteSpace { get; set; }
        public string? Widows { get; set; }
        public string? Width { get; set; }
        public string? WordBreak { get; set; }
        public string? WordSpacing { get; set; }
        public string? WordWrap { get; set; }
        public string? WritingMode { get; set; }
        public string? ZIndex { get; set; }
        public string? Zoom { get; set; }
    }
}